-- Immutable, auditable records for deterministic atomic-consensus analysis.
CREATE TABLE IF NOT EXISTS atomic_run (id INTEGER PRIMARY KEY, status TEXT NOT NULL, corpus_ref TEXT NOT NULL, corpus_git_rev TEXT NOT NULL, cutoff_at TEXT NOT NULL, versions_json TEXT NOT NULL, hashes_json TEXT NOT NULL, estimator_status TEXT NOT NULL DEFAULT 'not_run', evaluation_status TEXT NOT NULL DEFAULT 'pending', created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS atomic_aspect_assignment (run_id INTEGER NOT NULL, article_id INTEGER NOT NULL, event_id INTEGER, aspect TEXT NOT NULL, rule TEXT NOT NULL, unknown_reason TEXT, PRIMARY KEY(run_id, article_id), FOREIGN KEY(run_id) REFERENCES atomic_run(id));
CREATE TABLE IF NOT EXISTS atomic_occurrence (id TEXT PRIMARY KEY, run_id INTEGER NOT NULL, article_id INTEGER NOT NULL, event_id INTEGER, aspect TEXT NOT NULL, subject TEXT, predicate TEXT, object_text TEXT, polarity TEXT NOT NULL, modality TEXT NOT NULL, attribution TEXT, quantity TEXT, time_text TEXT, location TEXT, span_start INTEGER NOT NULL, span_end INTEGER NOT NULL, rule TEXT NOT NULL, abstention_reason TEXT, FOREIGN KEY(run_id) REFERENCES atomic_run(id));
CREATE TABLE IF NOT EXISTS atomic_scu (id TEXT PRIMARY KEY, run_id INTEGER NOT NULL, event_id INTEGER NOT NULL, aspect TEXT NOT NULL, canonical_key TEXT NOT NULL, display TEXT NOT NULL, classification TEXT, has_dispute INTEGER NOT NULL DEFAULT 0, FOREIGN KEY(run_id) REFERENCES atomic_run(id));
CREATE TABLE IF NOT EXISTS atomic_relation (run_id INTEGER NOT NULL, left_occurrence_id TEXT NOT NULL, right_occurrence_id TEXT NOT NULL, relation TEXT NOT NULL, rule TEXT NOT NULL, PRIMARY KEY(run_id, left_occurrence_id, right_occurrence_id), FOREIGN KEY(run_id) REFERENCES atomic_run(id));
CREATE TABLE IF NOT EXISTS atomic_reporting_group (id TEXT PRIMARY KEY, run_id INTEGER NOT NULL, method TEXT NOT NULL, owner TEXT, lineage_evidence TEXT, home_stratum TEXT, FOREIGN KEY(run_id) REFERENCES atomic_run(id));
CREATE TABLE IF NOT EXISTS atomic_reporting_group_member (group_id TEXT NOT NULL, article_id INTEGER NOT NULL, outlet_id INTEGER NOT NULL, PRIMARY KEY(group_id, article_id), FOREIGN KEY(group_id) REFERENCES atomic_reporting_group(id));
CREATE TABLE IF NOT EXISTS atomic_coverage (run_id INTEGER NOT NULL, event_id INTEGER NOT NULL, aspect TEXT NOT NULL, group_id TEXT NOT NULL, state TEXT NOT NULL, reason TEXT, cutoff_at TEXT NOT NULL, PRIMARY KEY(run_id,event_id,aspect,group_id));
CREATE TABLE IF NOT EXISTS atomic_scu_observation (run_id INTEGER NOT NULL, scu_id TEXT NOT NULL, group_id TEXT NOT NULL, state TEXT NOT NULL, occurrence_ids_json TEXT NOT NULL, PRIMARY KEY(run_id,scu_id,group_id));
CREATE TABLE IF NOT EXISTS atomic_panel (id TEXT PRIMARY KEY, run_id INTEGER NOT NULL, roster_json TEXT NOT NULL, strata_json TEXT NOT NULL, weights_json TEXT NOT NULL, unrated_policy TEXT NOT NULL, provenance_json TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS atomic_profile (run_id INTEGER NOT NULL, event_id INTEGER NOT NULL, outlet_id INTEGER NOT NULL, states_json TEXT NOT NULL, leave_out_json TEXT NOT NULL, PRIMARY KEY(run_id,event_id,outlet_id));
CREATE TABLE IF NOT EXISTS atomic_scu_result (run_id INTEGER NOT NULL, scu_id TEXT NOT NULL, support_json TEXT NOT NULL, sensitivity_json TEXT NOT NULL, modeled_core_membership REAL, PRIMARY KEY(run_id,scu_id));
